{
 "title": "Starlink",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Info and Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Dishy Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "starlink_dishy_bootcount" }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "starlink_dishy_alerts" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 18, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "starlink_dishy_alert_status", "legendFormat": "{{alert}}" }
   ]
  },
  {
   "title": "Obstruction Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dishy_avg_prolonged_obstruction_duration_s"
    }
   ]
  },
  {
   "title": "Outages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(starlink_dishy_outages)" }
   ]
  },
  {
   "title": "Observable Outages",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 10, "x": 3, "y": 7 },
   "targets": [
    {
     "expr": "max(starlink_dishy_outage[30s])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Outage Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "starlink_dishy_outage_duration_sec_sum",
     "legendFormat": "{{cause}}"
    }
   ]
  },
  { "title": "Outages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Outage Durations",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(starlink_dishy_outage_times_bucket) by (le) > 0",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Outage Counts Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "increase(starlink_dishy_outages)",
     "legendFormat": "{{cause}}"
    }
   ]
  },
  { "title": "Telemetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Pop Ping Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "starlink_dishy_pop_ping_latency_ms",
     "legendFormat": "Pop Ping Latency MS"
    },
    {
     "expr": "starlink_dishy_pop_ping_drop_rate",
     "legendFormat": "Pop Ping Packet Loss"
    }
   ]
  },
  {
   "title": "Dishy Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "starlink_dishy_downlink_throughput_bps",
     "legendFormat": "Downlink Throughput"
    },
    {
     "expr": "starlink_dishy_uplink_throughput_bps*-1",
     "legendFormat": "Uplink Throughput"
    }
   ]
  },
  {
   "title": "Azimuth",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "starlink_dishy_boresight_azimuth_deg"
    }
   ]
  },
  {
   "title": "Elevation",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "starlink_dishy_boresight_elevation_deg"
    }
   ]
  }
 ]
}